version: "3"

services:


  redis:
    container_name: redisCon
    image: redis
    restart: always
    environment:
      REDIS_HOST: redis
    ports:
    - "6378:6379"
#    - "6378:6378"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : Ammi@786
      MYSQL_DATABASE : fundoonotes
    ports:
      - "3306:3306"
#      - "3305:3305"

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
#      - "5672:5672"
      - "5671:5671"

  myprojectimage:
    container_name: fundooCon
    image: imagefundoo:latest
    command: bash -c " sleep 60 && python manage.py makemigrations && sleep 60 && python manage.py migrate && sleep 60 && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
      - redis
#      - rabbitmq
#      - nginx
    ports:
      - "8000:8000"
#    restart: unless-stopped
  nginx:
    image: nginx:latest
#    dockerfile: DockerfileNginxx
    depends_on:
      - myprojectimage
    ports:
      - "80:8000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080