AWS_UPLOAD_BUCKET = "infobeginner"
AWS_UPLOAD_USERNAME = "infobeginer"
AWS_UPLOAD_GROUP = "aws-infobeginner"
AWS_UPLOAD_REGION = 'us-south-1'
AWS_UPLOAD_ACCESS_KEY_ID = "AKIA5ZHMBPBHKQH4RVKB"
AWS_UPLOAD_SECRET_KEY = "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"