# Generated by Django 2.2 on 2019-12-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='s3_image_link',
            new_name='image_link',
        ),
    ]
