# Generated by Django 2.0 on 2019-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=22)),
                ('MobileNumber', models.CharField(max_length=2200)),
                ('Address', models.CharField(max_length=24)),
            ],
        ),
    ]
