# Generated by Django 2.0.2 on 2019-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0002_delete_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=22)),
                ('MobileNumber', models.CharField(max_length=2200)),
                ('Address', models.CharField(max_length=24)),
            ],
        ),
    ]
