# Generated by Django 2.0.2 on 2019-12-02 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=30)),
                ('directory', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='lable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('remainder', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('trash', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('collaborate', models.ManyToManyField(blank=True, null=True, related_name='collaborated_user', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(blank=True, null=True, related_name='collaborated_user', to='note.Label')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
