# Generated by Django 2.0.2 on 2019-12-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
    ]
