# Generated by Django 2.0 on 2019-11-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='File',
        ),
    ]
