# Generated by Django 2.2 on 2019-12-19 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 15, 28, 56, 749762), null=True),
        ),
    ]
