# Generated by Django 2.2 on 2019-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField(max_length=250)),
            ],
        ),
    ]
