# Generated by Django 2.0.2 on 2019-12-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_notes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='remainder',
            new_name='reminder',
        ),
    ]
