# Generated by Django 2.0 on 2019-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20191123_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=30)),
                ('directory', models.CharField(max_length=10)),
            ],
        ),
    ]
