# Generated by Django 2.2 on 2019-12-19 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20191219_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 16, 46, 22, 355617), null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 16, 46, 22, 355676), null=True),
        ),
    ]
