# Generated by Django 2.2 on 2019-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20191219_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Reminder date'),
        ),
    ]
