# Generated by Django 2.2 on 2019-12-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20191219_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'label', 'verbose_name_plural': 'labels'},
        ),
    ]
