# Generated by Django 2.2 on 2019-12-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociallogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
