# Generated by Django 2.0.2 on 2019-12-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociallogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=500, verbose_name='Use Id')),
                ('provider', models.CharField(max_length=500, verbose_name='Service Provider')),
                ('username', models.CharField(max_length=500, verbose_name='Username')),
                ('full_name', models.CharField(max_length=500, verbose_name='Completename ')),
                ('EXTRA_PARAMS', models.TextField(max_length=1000, verbose_name='Text Field')),
            ],
            options={
                'verbose_name': 'Social Login',
                'verbose_name_plural': 'Social Login',
            },
        ),
    ]
