# Generated by Django 2.0 on 2019-11-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=22)),
                ('Address', models.CharField(max_length=22)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
