# Generated by Django 2.0.2 on 2019-12-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0002_auto_20191123_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
